name: Node CI/CD to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📅 Checkout Code
        uses: actions/checkout@v2

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🛆 Install dependencies
        run: npm install

      - name: 🦪 Run tests (placeholder)
        run: echo "No tests defined"

      - name: 🚀 Trigger Railway Deploy Hook
        run: |
          curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}